spring:
  application:
    name: region-service
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_DOMAIN}:3306/region_db_daengdaeng_eodiga_core?&rewriteBatchedStatements=true
    username: root
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_ID}
            client-secret: ${GOOGLE_OAUTH_SECRET}
            redirect-uri: ${DOMAIN}/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_OAUTH_ID}
            client-secret: ${KAKAO_OAUTH_SECRET}
            redirect-uri: ${DOMAIN}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



  jwt:
    secret: ${SECURITY_SECRET}


  data:
    redis:
      host: ${REDIS_DOMAIN}
      port: 6379
      password: ${REDIS_PWD}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

kakao:
  api:
    url: "https://dapi.kakao.com/v2/local/geo/coord2address.json"
    key: ${KAKAO_REST_API_KEY}
    Nopeurl: "https://dapi.kakao.com/v2/local/search/address.json?query="

logging:
  level:
    org:
    springframework:
      security: DEBUG


cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key:  ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    url: ${AWS_S3_URL}
  stack:
    auto: false

frontend:
  url: ${FRONTEND_URL}
  test : ${TEST}

jwt:
  token-expiration:
    access: 86400000
    refresh: 1209600000

server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b %D"
      max-days: 14
    basedir: .

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
